import type { Config } from 'tailwindcss'

export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        surface: '#131313',
        'surface-dim': '#131313',
        'surface-bright': '#393939',
        'surface-container-lowest': '#0e0e0e',
        'surface-container-low': '#1c1b1b',
        'surface-container': '#201f1f',
        'surface-container-high': '#2a2a2a',
        'surface-container-highest': '#353534',
        'on-surface': '#e5e2e1',
        'on-surface-variant': '#d0c5af',
        'inverse-surface': '#e5e2e1',
        'inverse-on-surface': '#313030',
        outline: '#99907c',
        'outline-variant': '#4d4635',
        'surface-tint': '#e9c349',
        primary: '#f2ca50',
        'on-primary': '#3c2f00',
        'primary-container': '#d4af37',
        'on-primary-container': '#554300',
        'inverse-primary': '#735c00',
        secondary: '#eac249',
        'on-secondary': '#3d2f00',
        'secondary-container': '#b08c10',
        'on-secondary-container': '#352800',
        tertiary: '#d0cdcd',
        'on-tertiary': '#303030',
        'tertiary-container': '#b4b2b2',
        'on-tertiary-container': '#454544',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'primary-fixed': '#ffe088',
        'primary-fixed-dim': '#e9c349',
        'on-primary-fixed': '#241a00',
        'on-primary-fixed-variant': '#574500',
        'secondary-fixed': '#ffe08b',
        'secondary-fixed-dim': '#eac249',
        'on-secondary-fixed': '#241a00',
        'on-secondary-fixed-variant': '#584400',
        'tertiary-fixed': '#e5e2e1',
        'tertiary-fixed-dim': '#c8c6c5',
        'on-tertiary-fixed': '#1b1b1c',
        'on-tertiary-fixed-variant': '#474746',
        background: '#131313',
        'on-background': '#e5e2e1',
        'surface-variant': '#353534',
      },
      fontFamily: {
        serif: ['"Playfair Display"', 'Georgia', 'serif'],
        sans: ['Manrope', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'headline-xl': ['64px', { lineHeight: '72px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'headline-lg-mobile': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'headline-md': ['32px', { lineHeight: '40px', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.15em', fontWeight: '700' }],
      },
      borderRadius: {
        sm: '0.125rem',
        DEFAULT: '0.25rem',
        md: '0.375rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'container-max': '1280px',
        gutter: '24px',
        'margin-desktop': '80px',
        'margin-mobile': '20px',
      },
      maxWidth: {
        container: '1280px',
      },
      backdropBlur: {
        glass: '20px',
      },
    },
  },
  plugins: [],
} satisfies Config
